import { Inter } from 'next/font/google'
import './globals.css'

import NextAuthProvider from "@/providers/next-auth-provider";
// import NextThemeProvider from "@/providers/theme-provider";
import GlobalState from "@/context";
import Header from "@/components/header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <NextAuthProvider>
            <GlobalState>
              <Header/>
              {children}
            </GlobalState>
          </NextAuthProvider>
        
        </body>
    </html>
  )
}
